// lib/core/master_data/education.dart
// WORLD'S MOST COMPREHENSIVE EDUCATION MASTER DATA
// Complete coverage: Basic Education → Higher Education → All Degrees → All Subjects

class EducationMasterData {
  // ==================== BASIC EDUCATION LEVELS ====================
  static const List<String> basicEducationLevels = [
    'No Formal Education',
    'Below 5th',
    '5th Pass',
    '8th Pass',
    '10th Pass',
  ];

  // ==================== 10TH DETAILS ====================
  static const List<String> tenthBoards = [
    'CBSE',
    'ICSE',
    'UP Board',
    'MP Board',
    'Bihar Board',
    'Rajasthan Board',
    'Maharashtra Board',
    'Gujarat Board',
    'Tamil Nadu Board',
    'Karnataka Board',
    'Andhra Board',
    'Telangana Board',
    'West Bengal Board',
    'Punjab Board',
    'Haryana Board',
    'Delhi Board',
    'Assam Board',
    'Odisha Board',
    'Kerala Board',
    'Jharkhand Board',
    'Chhattisgarh Board',
    'Uttarakhand Board',
    'Himachal Board',
    'Jammu Kashmir Board',
    'Other State Board',
    'National Institute of Open Schooling (NIOS)',
  ];

  // ==================== 12TH STREAMS & SUBJECTS ====================
  static const Map<String, List<String>> twelfthStreamsWithSubjects = {
    'Science (Mathematics)': [
      'Physics',
      'Chemistry',
      'Mathematics',
      'English',
      'Computer Science',
      'Physical Education',
      'Hindi',
      'Biology (Optional)',
      'Economics (Optional)',
      'Information Technology',
      'Engineering Drawing',
      'Statistics',
    ],
    'Science (Biology)': [
      'Physics',
      'Chemistry',
      'Biology',
      'English',
      'Physical Education',
      'Hindi',
      'Computer Science (Optional)',
      'Mathematics (Optional)',
      'Biotechnology',
      'Home Science',
      'Psychology',
    ],
    'Science (Computer Science)': [
      'Physics',
      'Chemistry',
      'Mathematics',
      'Computer Science',
      'English',
      'Physical Education',
      'Information Technology',
      'Web Development',
      'Programming in Python',
      'Database Management',
    ],
    'Commerce': [
      'Accountancy',
      'Business Studies',
      'Economics',
      'Mathematics',
      'English',
      'Physical Education',
      'Computer Applications',
      'Entrepreneurship',
      'Marketing',
      'Taxation',
      'Cost Accounting',
      'Financial Management',
      'Statistics',
      'Legal Studies',
      'Banking and Insurance',
    ],
    'Arts/Humanities': [
      'History',
      'Geography',
      'Political Science',
      'Economics',
      'Sociology',
      'Psychology',
      'English',
      'Hindi',
      'Sanskrit',
      'Urdu',
      'Philosophy',
      'Physical Education',
      'Home Science',
      'Fine Arts',
      'Music',
      'Dance',
      'Theatre',
      'Journalism',
      'Mass Communication',
      'Public Administration',
      'Social Work',
      'Anthropology',
      'Archaeology',
      'Linguistics',
    ],
    'Vocational': [
      'Information Technology',
      'Retail Management',
      'Automobile Technology',
      'Healthcare',
      'Tourism',
      'Hospitality Management',
      'Agriculture',
      'Food Processing',
      'Textile Design',
      'Fashion Studies',
      'Electronics',
      'Electrical Technology',
      'Civil Engineering (Vocational)',
      'Mechanical Engineering (Vocational)',
      'Computer Applications',
    ],
  };

  static const List<String> twelfthBoards = [
    'CBSE',
    'ICSE',
    'UP Board',
    'MP Board',
    'Bihar Board',
    'Rajasthan Board',
    'Maharashtra Board',
    'Gujarat Board',
    'Tamil Nadu Board',
    'Karnataka Board',
    'Andhra Board',
    'Telangana Board',
    'West Bengal Board',
    'Punjab Board',
    'Haryana Board',
    'Delhi Board',
    'Assam Board',
    'Odisha Board',
    'Kerala Board',
    'Jharkhand Board',
    'Chhattisgarh Board',
    'Uttarakhand Board',
    'Himachal Board',
    'Jammu Kashmir Board',
    'Other State Board',
    'NIOS',
    'IB Diploma Programme',
    'Cambridge International (A/AS Levels)',
    'IGCSE',
  ];

  // ==================== ALL DEGREES MASTER LIST ====================
  static const List<Map<String, dynamic>> allDegrees = [
    // BACHELOR'S DEGREES
    {
      'code': 'B001',
      'name': 'B.Tech',
      'fullName': 'Bachelor of Technology',
      'type': 'Engineering',
      'duration': '4 years',
    },
    {
      'code': 'B002',
      'name': 'B.E.',
      'fullName': 'Bachelor of Engineering',
      'type': 'Engineering',
      'duration': '4 years',
    },
    {
      'code': 'B003',
      'name': 'B.Sc',
      'fullName': 'Bachelor of Science',
      'type': 'Science',
      'duration': '3 years',
    },
    {
      'code': 'B004',
      'name': 'B.Com',
      'fullName': 'Bachelor of Commerce',
      'type': 'Commerce',
      'duration': '3 years',
    },
    {
      'code': 'B005',
      'name': 'B.A.',
      'fullName': 'Bachelor of Arts',
      'type': 'Arts',
      'duration': '3 years',
    },
    {
      'code': 'B006',
      'name': 'BBA',
      'fullName': 'Bachelor of Business Administration',
      'type': 'Management',
      'duration': '3 years',
    },
    {
      'code': 'B007',
      'name': 'BCA',
      'fullName': 'Bachelor of Computer Applications',
      'type': 'Computer',
      'duration': '3 years',
    },
    {
      'code': 'B008',
      'name': 'B.Pharma',
      'fullName': 'Bachelor of Pharmacy',
      'type': 'Medical',
      'duration': '4 years',
    },
    {
      'code': 'B009',
      'name': 'B.Arch',
      'fullName': 'Bachelor of Architecture',
      'type': 'Architecture',
      'duration': '5 years',
    },
    {
      'code': 'B010',
      'name': 'B.Des',
      'fullName': 'Bachelor of Design',
      'type': 'Design',
      'duration': '4 years',
    },
    {
      'code': 'B011',
      'name': 'B.Plan',
      'fullName': 'Bachelor of Planning',
      'type': 'Planning',
      'duration': '4 years',
    },
    {
      'code': 'B012',
      'name': 'B.H.M.',
      'fullName': 'Bachelor of Hotel Management',
      'type': 'Hospitality',
      'duration': '4 years',
    },
    {
      'code': 'B013',
      'name': 'B.Ed',
      'fullName': 'Bachelor of Education',
      'type': 'Education',
      'duration': '2 years',
    },
    {
      'code': 'B014',
      'name': 'B.P.Ed',
      'fullName': 'Bachelor of Physical Education',
      'type': 'Sports',
      'duration': '3 years',
    },
    {
      'code': 'B015',
      'name': 'B.Lib',
      'fullName': 'Bachelor of Library Science',
      'type': 'Library',
      'duration': '1 year',
    },
    {
      'code': 'B016',
      'name': 'B.F.A.',
      'fullName': 'Bachelor of Fine Arts',
      'type': 'Arts',
      'duration': '4 years',
    },
    {
      'code': 'B017',
      'name': 'B.J.M.C.',
      'fullName': 'Bachelor of Journalism & Mass Communication',
      'type': 'Media',
      'duration': '3 years',
    },
    {
      'code': 'B018',
      'name': 'B.S.W.',
      'fullName': 'Bachelor of Social Work',
      'type': 'Social Work',
      'duration': '3 years',
    },
    {
      'code': 'B019',
      'name': 'LL.B.',
      'fullName': 'Bachelor of Laws',
      'type': 'Law',
      'duration': '3 years',
    },
    {
      'code': 'B020',
      'name': 'B.A.LL.B',
      'fullName': 'Bachelor of Arts + Bachelor of Laws',
      'type': 'Law',
      'duration': '5 years',
    },
    {
      'code': 'B021',
      'name': 'B.Com.LL.B',
      'fullName': 'Bachelor of Commerce + Bachelor of Laws',
      'type': 'Law',
      'duration': '5 years',
    },
    {
      'code': 'B022',
      'name': 'B.B.A.LL.B',
      'fullName': 'Bachelor of Business Admin + Laws',
      'type': 'Law',
      'duration': '5 years',
    },
    {
      'code': 'B023',
      'name': 'MBBS',
      'fullName': 'Bachelor of Medicine & Surgery',
      'type': 'Medical',
      'duration': '5.5 years',
    },
    {
      'code': 'B024',
      'name': 'BDS',
      'fullName': 'Bachelor of Dental Surgery',
      'type': 'Medical',
      'duration': '5 years',
    },
    {
      'code': 'B025',
      'name': 'BHMS',
      'fullName': 'Bachelor of Homeopathy Medicine',
      'type': 'Medical',
      'duration': '5.5 years',
    },
    {
      'code': 'B026',
      'name': 'BAMS',
      'fullName': 'Bachelor of Ayurvedic Medicine',
      'type': 'Medical',
      'duration': '5.5 years',
    },
    {
      'code': 'B027',
      'name': 'BUMS',
      'fullName': 'Bachelor of Unani Medicine',
      'type': 'Medical',
      'duration': '5.5 years',
    },
    {
      'code': 'B028',
      'name': 'B.V.Sc.',
      'fullName': 'Bachelor of Veterinary Science',
      'type': 'Medical',
      'duration': '5.5 years',
    },
    {
      'code': 'B029',
      'name': 'B.P.T.',
      'fullName': 'Bachelor of Physiotherapy',
      'type': 'Medical',
      'duration': '4.5 years',
    },
    {
      'code': 'B030',
      'name': 'B.O.T.',
      'fullName': 'Bachelor of Occupational Therapy',
      'type': 'Medical',
      'duration': '4.5 years',
    },
    {
      'code': 'B031',
      'name': 'B.Sc Nursing',
      'fullName': 'Bachelor of Science in Nursing',
      'type': 'Medical',
      'duration': '4 years',
    },
    {
      'code': 'B032',
      'name': 'B.Optom',
      'fullName': 'Bachelor of Optometry',
      'type': 'Medical',
      'duration': '4 years',
    },
    {
      'code': 'B033',
      'name': 'B.M.L.T.',
      'fullName': 'Bachelor of Medical Lab Technology',
      'type': 'Medical',
      'duration': '3 years',
    },
    {
      'code': 'B034',
      'name': 'B.Sc Agriculture',
      'fullName': 'Bachelor of Science in Agriculture',
      'type': 'Agriculture',
      'duration': '4 years',
    },
    {
      'code': 'B035',
      'name': 'B.Sc Horticulture',
      'fullName': 'Bachelor of Science in Horticulture',
      'type': 'Agriculture',
      'duration': '4 years',
    },
    {
      'code': 'B036',
      'name': 'B.Sc Forestry',
      'fullName': 'Bachelor of Science in Forestry',
      'type': 'Agriculture',
      'duration': '4 years',
    },
    {
      'code': 'B037',
      'name': 'B.F.Sc',
      'fullName': 'Bachelor of Fishery Science',
      'type': 'Agriculture',
      'duration': '4 years',
    },

    // MASTER'S DEGREES
    {
      'code': 'M001',
      'name': 'M.Tech',
      'fullName': 'Master of Technology',
      'type': 'Engineering',
      'duration': '2 years',
    },
    {
      'code': 'M002',
      'name': 'M.E.',
      'fullName': 'Master of Engineering',
      'type': 'Engineering',
      'duration': '2 years',
    },
    {
      'code': 'M003',
      'name': 'M.Sc',
      'fullName': 'Master of Science',
      'type': 'Science',
      'duration': '2 years',
    },
    {
      'code': 'M004',
      'name': 'M.Com',
      'fullName': 'Master of Commerce',
      'type': 'Commerce',
      'duration': '2 years',
    },
    {
      'code': 'M005',
      'name': 'M.A.',
      'fullName': 'Master of Arts',
      'type': 'Arts',
      'duration': '2 years',
    },
    {
      'code': 'M006',
      'name': 'MBA',
      'fullName': 'Master of Business Administration',
      'type': 'Management',
      'duration': '2 years',
    },
    {
      'code': 'M007',
      'name': 'MCA',
      'fullName': 'Master of Computer Applications',
      'type': 'Computer',
      'duration': '3 years',
    },
    {
      'code': 'M008',
      'name': 'M.Pharma',
      'fullName': 'Master of Pharmacy',
      'type': 'Medical',
      'duration': '2 years',
    },
    {
      'code': 'M009',
      'name': 'M.Arch',
      'fullName': 'Master of Architecture',
      'type': 'Architecture',
      'duration': '2 years',
    },
    {
      'code': 'M010',
      'name': 'M.Des',
      'fullName': 'Master of Design',
      'type': 'Design',
      'duration': '2 years',
    },
    {
      'code': 'M011',
      'name': 'M.Plan',
      'fullName': 'Master of Planning',
      'type': 'Planning',
      'duration': '2 years',
    },
    {
      'code': 'M012',
      'name': 'M.H.M.',
      'fullName': 'Master of Hotel Management',
      'type': 'Hospitality',
      'duration': '2 years',
    },
    {
      'code': 'M013',
      'name': 'M.Ed',
      'fullName': 'Master of Education',
      'type': 'Education',
      'duration': '2 years',
    },
    {
      'code': 'M014',
      'name': 'M.P.Ed',
      'fullName': 'Master of Physical Education',
      'type': 'Sports',
      'duration': '2 years',
    },
    {
      'code': 'M015',
      'name': 'M.Lib',
      'fullName': 'Master of Library Science',
      'type': 'Library',
      'duration': '1 year',
    },
    {
      'code': 'M016',
      'name': 'M.F.A.',
      'fullName': 'Master of Fine Arts',
      'type': 'Arts',
      'duration': '2 years',
    },
    {
      'code': 'M017',
      'name': 'M.J.M.C.',
      'fullName': 'Master of Journalism & Mass Comm',
      'type': 'Media',
      'duration': '2 years',
    },
    {
      'code': 'M018',
      'name': 'M.S.W.',
      'fullName': 'Master of Social Work',
      'type': 'Social Work',
      'duration': '2 years',
    },
    {
      'code': 'M019',
      'name': 'LL.M.',
      'fullName': 'Master of Laws',
      'type': 'Law',
      'duration': '2 years',
    },
    {
      'code': 'M020',
      'name': 'MD',
      'fullName': 'Doctor of Medicine',
      'type': 'Medical',
      'duration': '3 years',
    },
    {
      'code': 'M021',
      'name': 'MS',
      'fullName': 'Master of Surgery',
      'type': 'Medical',
      'duration': '3 years',
    },
    {
      'code': 'M022',
      'name': 'MDS',
      'fullName': 'Master of Dental Surgery',
      'type': 'Medical',
      'duration': '3 years',
    },
    {
      'code': 'M023',
      'name': 'M.P.T.',
      'fullName': 'Master of Physiotherapy',
      'type': 'Medical',
      'duration': '2 years',
    },
    {
      'code': 'M024',
      'name': 'M.Sc Nursing',
      'fullName': 'Master of Science in Nursing',
      'type': 'Medical',
      'duration': '2 years',
    },

    // DOCTORAL DEGREES
    {
      'code': 'D001',
      'name': 'PhD',
      'fullName': 'Doctor of Philosophy',
      'type': 'Doctoral',
      'duration': '3-5 years',
    },
    {
      'code': 'D002',
      'name': 'M.Phil',
      'fullName': 'Master of Philosophy',
      'type': 'Doctoral',
      'duration': '1-2 years',
    },
    {
      'code': 'D003',
      'name': 'D.Sc',
      'fullName': 'Doctor of Science',
      'type': 'Doctoral',
      'duration': '3-5 years',
    },
    {
      'code': 'D004',
      'name': 'D.Litt',
      'fullName': 'Doctor of Literature',
      'type': 'Doctoral',
      'duration': '3-5 years',
    },
    {
      'code': 'D005',
      'name': 'DBA',
      'fullName': 'Doctor of Business Administration',
      'type': 'Doctoral',
      'duration': '3-5 years',
    },
    {
      'code': 'D006',
      'name': 'D.M.A.',
      'fullName': 'Doctor of Musical Arts',
      'type': 'Doctoral',
      'duration': '3-5 years',
    },
    {
      'code': 'D007',
      'name': 'Ed.D',
      'fullName': 'Doctor of Education',
      'type': 'Doctoral',
      'duration': '3-5 years',
    },
    {
      'code': 'D008',
      'name': 'D.Eng',
      'fullName': 'Doctor of Engineering',
      'type': 'Doctoral',
      'duration': '3-5 years',
    },

    // PROFESSIONAL COURSES
    {
      'code': 'P001',
      'name': 'CA',
      'fullName': 'Chartered Accountancy',
      'type': 'Professional',
      'duration': '3-5 years',
    },
    {
      'code': 'P002',
      'name': 'CS',
      'fullName': 'Company Secretary',
      'type': 'Professional',
      'duration': '3 years',
    },
    {
      'code': 'P003',
      'name': 'CMA',
      'fullName': 'Cost and Management Accountant',
      'type': 'Professional',
      'duration': '3 years',
    },
    {
      'code': 'P004',
      'name': 'ICWA',
      'fullName': 'Institute of Cost and Works Accountants',
      'type': 'Professional',
      'duration': '3 years',
    },
    {
      'code': 'P005',
      'name': 'CFA',
      'fullName': 'Chartered Financial Analyst',
      'type': 'Professional',
      'duration': '2-3 years',
    },
    {
      'code': 'P006',
      'name': 'FRM',
      'fullName': 'Financial Risk Manager',
      'type': 'Professional',
      'duration': '1-2 years',
    },
    {
      'code': 'P007',
      'name': 'CPA',
      'fullName': 'Certified Public Accountant',
      'type': 'Professional',
      'duration': '1-2 years',
    },
    {
      'code': 'P008',
      'name': 'ACCA',
      'fullName': 'Association of Chartered Certified Accountants',
      'type': 'Professional',
      'duration': '2-3 years',
    },
    {
      'code': 'P009',
      'name': 'PGDM',
      'fullName': 'Post Graduate Diploma in Management',
      'type': 'Professional',
      'duration': '2 years',
    },
    {
      'code': 'P010',
      'name': 'PGDBM',
      'fullName': 'Post Graduate Diploma in Business Management',
      'type': 'Professional',
      'duration': '2 years',
    },
    {
      'code': 'P011',
      'name': 'PGDCA',
      'fullName': 'Post Graduate Diploma in Computer Applications',
      'type': 'Professional',
      'duration': '1 year',
    },
    {
      'code': 'P012',
      'name': 'PGDIT',
      'fullName': 'Post Graduate Diploma in Information Technology',
      'type': 'Professional',
      'duration': '1 year',
    },
    {
      'code': 'P013',
      'name': 'PGDHRM',
      'fullName': 'Post Graduate Diploma in HR Management',
      'type': 'Professional',
      'duration': '1 year',
    },
    {
      'code': 'P014',
      'name': 'PGDMarketing',
      'fullName': 'Post Graduate Diploma in Marketing',
      'type': 'Professional',
      'duration': '1 year',
    },
    {
      'code': 'P015',
      'name': 'PGDFinance',
      'fullName': 'Post Graduate Diploma in Finance',
      'type': 'Professional',
      'duration': '1 year',
    },
  ];

  // ==================== ENGINEERING BRANCHES (B.Tech/B.E) ====================
  static const List<String> engineeringBranches = [
    'Computer Science Engineering (CSE)',
    'Information Technology (IT)',
    'Electronics & Communication Engineering (ECE)',
    'Electrical Engineering (EE)',
    'Mechanical Engineering (ME)',
    'Civil Engineering (CE)',
    'Automobile Engineering',
    'Aerospace Engineering',
    'Chemical Engineering',
    'Petroleum Engineering',
    'Biotechnology Engineering',
    'Biomedical Engineering',
    'Artificial Intelligence & Machine Learning (AI/ML)',
    'Data Science Engineering',
    'Cyber Security Engineering',
    'Cloud Computing Engineering',
    'Robotics Engineering',
    'Mechatronics Engineering',
    'Textile Engineering',
    'Metallurgical Engineering',
    'Mining Engineering',
    'Instrumentation Engineering',
    'Production Engineering',
    'Industrial Engineering',
    'Agricultural Engineering',
    'Food Technology Engineering',
    'Environmental Engineering',
    'Marine Engineering',
    'Naval Architecture',
    'Power Engineering',
    'Electronics Engineering',
    'Telecommunication Engineering',
    'VLSI Design Engineering',
    'Embedded Systems Engineering',
    'Internet of Things (IoT) Engineering',
    'Blockchain Engineering',
    'Quantum Computing Engineering',
  ];

  // ==================== SCIENCE SUBJECTS (B.Sc) ====================
  static const List<String> scienceSubjects = [
    'Physics',
    'Chemistry',
    'Mathematics',
    'Biology',
    'Computer Science',
    'Information Technology',
    'Biotechnology',
    'Microbiology',
    'Biochemistry',
    'Botany',
    'Zoology',
    'Environmental Science',
    'Geology',
    'Statistics',
    'Electronics',
    'Food Science',
    'Nutrition',
    'Forensic Science',
    'Genetics',
    'Molecular Biology',
    'Bioinformatics',
    'Psychology',
    'Home Science',
    'Fashion Technology',
    'Textile Science',
    'Agriculture',
    'Horticulture',
    'Forestry',
    'Fisheries',
    'Dairy Science',
    'Animal Husbandry',
    'Veterinary Science',
    'Nursing',
    'Medical Lab Technology',
    'Radiology',
    'Optometry',
    'Physiotherapy',
    'Occupational Therapy',
    'Audiology',
    'Speech Therapy',
    'Cardiovascular Technology',
    'Dialysis Technology',
    'Operation Theatre Technology',
    'Anesthesia Technology',
    'Respiratory Therapy',
  ];

  // ==================== COMMERCE SUBJECTS (B.Com) ====================
  static const List<String> commerceSubjects = [
    'Accountancy',
    'Financial Accounting',
    'Cost Accounting',
    'Management Accounting',
    'Corporate Accounting',
    'Taxation',
    'Business Law',
    'Company Law',
    'Business Mathematics',
    'Business Statistics',
    'Economics',
    'Microeconomics',
    'Macroeconomics',
    'Indian Economy',
    'International Economics',
    'Business Economics',
    'Business Management',
    'Marketing Management',
    'Financial Management',
    'Human Resource Management',
    'Production Management',
    'Operations Management',
    'Entrepreneurship',
    'Business Ethics',
    'Corporate Governance',
    'Banking',
    'Insurance',
    'Auditing',
    'Financial Markets',
    'Investment Management',
    'International Business',
    'Export Import Management',
    'Supply Chain Management',
    'E-Commerce',
    'Digital Marketing',
    'Retail Management',
    'Business Communication',
    'Organizational Behavior',
    'Strategic Management',
    'Business Environment',
  ];

  // ==================== ARTS/HUMANITIES SUBJECTS (B.A.) ====================
  static const List<String> artsSubjects = [
    'Economics',
    'History',
    'Geography',
    'Political Science',
    'Sociology',
    'Psychology',
    'Philosophy',
    'Anthropology',
    'Archaeology',
    'Linguistics',
    'English Literature',
    'Hindi Literature',
    'Sanskrit Literature',
    'Urdu Literature',
    'Regional Languages (Bengali/Marathi/Telugu/Tamil/Gujarati/Kannada/Malayalam/Punjabi/Assamese/Odia)',
    'Public Administration',
    'International Relations',
    'Defense Studies',
    'Social Work',
    'Rural Development',
    'Gender Studies',
    'Women Studies',
    'Journalism',
    'Mass Communication',
    'Advertising',
    'Public Relations',
    'Film Studies',
    'Theatre Arts',
    'Music (Vocal/Instrumental)',
    'Dance (Classical/Folk)',
    'Fine Arts',
    'Painting',
    'Sculpture',
    'Applied Arts',
    'Photography',
    'Physical Education',
    'Sports Management',
    'Yoga',
    'Tourism Management',
    'Hotel Management',
    'Event Management',
    'Hospitality Management',
    'Library Science',
    'Museum Studies',
    'Archival Studies',
    'Criminology',
    'Forensic Psychology',
    'Clinical Psychology',
    'Counseling Psychology',
    'Industrial Psychology',
    'Educational Psychology',
    'Child Psychology',
  ];

  // ==================== MANAGEMENT SUBJECTS (BBA/MBA) ====================
  static const List<String> managementSubjects = [
    'Principles of Management',
    'Organizational Behavior',
    'Business Communication',
    'Business Mathematics',
    'Business Statistics',
    'Managerial Economics',
    'Financial Accounting',
    'Cost Accounting',
    'Management Accounting',
    'Marketing Management',
    'Financial Management',
    'Human Resource Management',
    'Production Management',
    'Operations Management',
    'Supply Chain Management',
    'International Business',
    'Business Law',
    'Corporate Governance',
    'Business Ethics',
    'Entrepreneurship',
    'Strategic Management',
    'Retail Management',
    'Sales Management',
    'Consumer Behavior',
    'Advertising Management',
    'Brand Management',
    'Digital Marketing',
    'Investment Management',
    'Banking and Insurance',
    'Taxation',
    'Business Research Methods',
    'Project Management',
    'Business Analytics',
    'Data Science for Business',
    'Artificial Intelligence in Business',
    'E-Commerce',
    'Startup Management',
    'Family Business Management',
    'Hospital Management',
    'Tourism Management',
    'Event Management',
  ];

  // ==================== COMPUTER APPLICATIONS SUBJECTS (BCA/MCA) ====================
  static const List<String> computerSubjects = [
    'Programming Fundamentals (C/C++)',
    'Object Oriented Programming (Java/C++)',
    'Python Programming',
    'Data Structures',
    'Algorithms',
    'Database Management Systems',
    'SQL',
    'NoSQL Databases',
    'Operating Systems',
    'Computer Networks',
    'Web Development (HTML/CSS/JS)',
    'React/Angular/Vue.js',
    'Node.js/PHP',
    'Mobile App Development (Flutter/Android/iOS)',
    'Software Engineering',
    'System Design',
    'Cloud Computing (AWS/Azure/GCP)',
    'DevOps',
    'Cyber Security',
    'Ethical Hacking',
    'Cryptography',
    'Blockchain Technology',
    'Artificial Intelligence',
    'Machine Learning',
    'Deep Learning',
    'Data Science',
    'Big Data Analytics (Hadoop/Spark)',
    'Internet of Things (IoT)',
    'Computer Graphics',
    'Multimedia',
    'Animation',
    'Game Development',
    'Digital Marketing',
    'SEO/SEM',
    'Social Media Marketing',
    'E-Commerce',
    'ERP Systems',
    'SAP',
    'Salesforce',
    'IT Project Management',
    'IT Infrastructure',
    'IT Service Management (ITIL)',
  ];

  // ==================== MEDICAL SUBJECTS (MBBS/BDS/B.Pharma) ====================
  static const List<String> medicalSubjects = [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Pathology',
    'Microbiology',
    'Pharmacology',
    'Forensic Medicine',
    'Community Medicine',
    'ENT',
    'Ophthalmology',
    'Medicine',
    'Surgery',
    'Pediatrics',
    'Obstetrics & Gynecology',
    'Orthopedics',
    'Radiology',
    'Anesthesiology',
    'Dermatology',
    'Psychiatry',
    'Dentistry',
    'Oral Medicine',
    'Oral Surgery',
    'Periodontics',
    'Orthodontics',
    'Endodontics',
    'Prosthodontics',
    'Pedodontics',
    'Oral Pathology',
    'Pharmaceutical Chemistry',
    'Pharmaceutics',
    'Pharmacognosy',
    'Clinical Pharmacy',
    'Hospital Pharmacy',
    'Drug Regulatory Affairs',
    'Nursing Fundamentals',
    'Medical-Surgical Nursing',
    'Community Health Nursing',
    'Pediatric Nursing',
    'Psychiatric Nursing',
    'Obstetric Nursing',
  ];

  // ==================== LAW SUBJECTS (LL.B/LL.M) ====================
  static const List<String> lawSubjects = [
    'Constitutional Law',
    'Criminal Law',
    'Civil Law',
    'Corporate Law',
    'Tax Law',
    'Labor Law',
    'Environmental Law',
    'International Law',
    'Human Rights Law',
    'Cyber Law',
    'Intellectual Property Law',
    'Contract Law',
    'Tort Law',
    'Property Law',
    'Family Law',
    'Evidence Law',
    'Procedural Law (CrPC/CrPC)',
    'Legal Ethics',
    'Moot Court',
    'Legal Research',
    'Legal Writing',
    'Alternative Dispute Resolution',
    'Banking Law',
    'Insurance Law',
    'Mergers & Acquisitions',
    'Competition Law',
    'Media Law',
    'Sports Law',
    'Maritime Law',
    'Air Law',
    'Space Law',
  ];

  // ==================== AGRICULTURE SUBJECTS ====================
  static const List<String> agricultureSubjects = [
    'Agronomy',
    'Soil Science',
    'Plant Pathology',
    'Entomology',
    'Horticulture',
    'Plant Breeding',
    'Genetics',
    'Biotechnology in Agriculture',
    'Agricultural Economics',
    'Agricultural Extension',
    'Farm Machinery',
    'Irrigation Engineering',
    'Crop Production',
    'Seed Technology',
    'Fertilizer Technology',
    'Pest Management',
    'Organic Farming',
    'Sustainable Agriculture',
    'Precision Agriculture',
    'Post Harvest Technology',
    'Food Processing',
    'Dairy Technology',
    'Poultry Science',
    'Fishery Science',
    'Sericulture',
    'Apiculture',
    'Forestry',
    'Agroforestry',
    'Silviculture',
    'Wildlife Management',
  ];

  // ==================== ITI TRADES ====================
  static const List<Map<String, String>> itiTrades = [
    {'code': '01', 'name': 'Fitter', 'duration': '2 years'},
    {'code': '02', 'name': 'Electrician', 'duration': '2 years'},
    {'code': '03', 'name': 'Wireman', 'duration': '2 years'},
    {'code': '04', 'name': 'Mechanic (Motor Vehicle)', 'duration': '2 years'},
    {'code': '05', 'name': 'Mechanic (Diesel)', 'duration': '2 years'},
    {
      'code': '06',
      'name': 'Mechanic (Refrigeration & AC)',
      'duration': '2 years',
    },
    {'code': '07', 'name': 'Welder', 'duration': '1 year'},
    {'code': '08', 'name': 'Carpenter', 'duration': '1 year'},
    {'code': '09', 'name': 'Plumber', 'duration': '1 year'},
    {
      'code': '10',
      'name': 'Computer Operator & Programming Assistant (COPA)',
      'duration': '1 year',
    },
    {'code': '11', 'name': 'Electronics Mechanic', 'duration': '2 years'},
    {
      'code': '12',
      'name': 'Information Technology (IT)',
      'duration': '2 years',
    },
    {
      'code': '13',
      'name': 'Computer Hardware & Network Maintenance',
      'duration': '2 years',
    },
    {'code': '14', 'name': 'Web Development', 'duration': '1 year'},
    {'code': '15', 'name': 'Digital Photography', 'duration': '1 year'},
    {
      'code': '16',
      'name': 'Multimedia Animation & Special Effects',
      'duration': '1 year',
    },
    {
      'code': '17',
      'name': 'Desktop Publishing Operator (DTP)',
      'duration': '1 year',
    },
    {'code': '18', 'name': 'Secretarial Practice', 'duration': '1 year'},
    {'code': '19', 'name': 'Stenography (English/Hindi)', 'duration': '1 year'},
    {'code': '20', 'name': 'Marketing Executive', 'duration': '1 year'},
    {'code': '21', 'name': 'Front Office Assistant', 'duration': '1 year'},
    {'code': '22', 'name': 'Hospitality Management', 'duration': '2 years'},
    {'code': '23', 'name': 'Food Production (Cook)', 'duration': '1 year'},
    {'code': '24', 'name': 'Food & Beverage Service', 'duration': '1 year'},
    {'code': '25', 'name': 'Housekeeping', 'duration': '1 year'},
    {'code': '26', 'name': 'Dress Making', 'duration': '1 year'},
    {
      'code': '27',
      'name': 'Fashion Design & Technology',
      'duration': '2 years',
    },
    {'code': '28', 'name': 'Hair & Skin Care', 'duration': '1 year'},
    {'code': '29', 'name': 'Beauty Therapy', 'duration': '1 year'},
    {'code': '30', 'name': 'Medical Lab Technician', 'duration': '2 years'},
    {'code': '31', 'name': 'X-Ray Technician', 'duration': '2 years'},
    {'code': '32', 'name': 'Dialysis Technician', 'duration': '2 years'},
    {
      'code': '33',
      'name': 'Operation Theatre Technician',
      'duration': '2 years',
    },
    {'code': '34', 'name': 'Physiotherapy Technician', 'duration': '2 years'},
    {'code': '35', 'name': 'Nursing Assistant', 'duration': '1 year'},
    {
      'code': '36',
      'name': 'Mason (Building Constructor)',
      'duration': '1 year',
    },
    {'code': '37', 'name': 'Painter (General)', 'duration': '1 year'},
    {'code': '38', 'name': 'Sheet Metal Worker', 'duration': '1 year'},
    {'code': '39', 'name': 'CNC Operator', 'duration': '1 year'},
    {'code': '40', 'name': 'Electric Vehicle Technician', 'duration': '1 year'},
  ];

  // ==================== DIPLOMA COURSES ====================
  static const List<Map<String, String>> diplomaCourses = [
    {
      'code': 'D001',
      'name': 'Diploma in Computer Engineering',
      'duration': '3 years',
    },
    {
      'code': 'D002',
      'name': 'Diploma in Information Technology',
      'duration': '3 years',
    },
    {
      'code': 'D003',
      'name': 'Diploma in Electronics & Communication',
      'duration': '3 years',
    },
    {
      'code': 'D004',
      'name': 'Diploma in Electrical Engineering',
      'duration': '3 years',
    },
    {
      'code': 'D005',
      'name': 'Diploma in Mechanical Engineering',
      'duration': '3 years',
    },
    {
      'code': 'D006',
      'name': 'Diploma in Civil Engineering',
      'duration': '3 years',
    },
    {
      'code': 'D007',
      'name': 'Diploma in Automobile Engineering',
      'duration': '3 years',
    },
    {
      'code': 'D008',
      'name': 'Diploma in Chemical Engineering',
      'duration': '3 years',
    },
    {
      'code': 'D009',
      'name': 'Diploma in Mining Engineering',
      'duration': '3 years',
    },
    {
      'code': 'D010',
      'name': 'Diploma in Textile Engineering',
      'duration': '3 years',
    },
    {
      'code': 'D011',
      'name': 'Diploma in Fashion Technology',
      'duration': '2 years',
    },
    {
      'code': 'D012',
      'name': 'Diploma in Interior Design',
      'duration': '2 years',
    },
    {
      'code': 'D013',
      'name': 'Diploma in Animation & Multimedia',
      'duration': '2 years',
    },
    {'code': 'D014', 'name': 'Diploma in Graphic Design', 'duration': '1 year'},
    {
      'code': 'D015',
      'name': 'Diploma in Web Development',
      'duration': '1 year',
    },
    {
      'code': 'D016',
      'name': 'Diploma in Digital Marketing',
      'duration': '1 year',
    },
    {
      'code': 'D017',
      'name': 'Diploma in Business Administration',
      'duration': '1 year',
    },
    {
      'code': 'D018',
      'name': 'Diploma in Hotel Management',
      'duration': '2 years',
    },
    {
      'code': 'D019',
      'name': 'Diploma in Medical Lab Technology',
      'duration': '2 years',
    },
    {
      'code': 'D020',
      'name': 'Diploma in Pharmacy (D.Pharm)',
      'duration': '2 years',
    },
    {'code': 'D021', 'name': 'Diploma in Nursing (GNM)', 'duration': '3 years'},
    {'code': 'D022', 'name': 'Diploma in Radiology', 'duration': '2 years'},
    {'code': 'D023', 'name': 'Diploma in Physiotherapy', 'duration': '2 years'},
    {'code': 'D024', 'name': 'Diploma in Agriculture', 'duration': '2 years'},
    {'code': 'D025', 'name': 'Diploma in Horticulture', 'duration': '2 years'},
    {'code': 'D026', 'name': 'Diploma in Forestry', 'duration': '2 years'},
    {'code': 'D027', 'name': 'Diploma in Fisheries', 'duration': '2 years'},
    {
      'code': 'D028',
      'name': 'Diploma in Veterinary Science',
      'duration': '2 years',
    },
    {
      'code': 'D029',
      'name': 'Diploma in Elementary Education (D.El.Ed)',
      'duration': '2 years',
    },
  ];

  // ==================== CERTIFICATIONS ====================
  static const List<Map<String, String>> certifications = [
    {
      'name': 'Certified Ethical Hacker (CEH)',
      'duration': '40 hours',
      'provider': 'EC-Council',
    },
    {
      'name': 'CompTIA Security+',
      'duration': '30 hours',
      'provider': 'CompTIA',
    },
    {'name': 'Cisco CCNA', 'duration': '120 hours', 'provider': 'Cisco'},
    {
      'name': 'AWS Solutions Architect',
      'duration': '80 hours',
      'provider': 'Amazon AWS',
    },
    {
      'name': 'Microsoft Azure Fundamentals',
      'duration': '40 hours',
      'provider': 'Microsoft',
    },
    {
      'name': 'Google Cloud Associate Engineer',
      'duration': '50 hours',
      'provider': 'Google Cloud',
    },
    {
      'name': 'Python Programming Certification',
      'duration': '60 hours',
      'provider': 'Python Institute',
    },
    {
      'name': 'Java Certification (OCJP)',
      'duration': '100 hours',
      'provider': 'Oracle',
    },
    {
      'name': 'Full Stack Web Development',
      'duration': '200 hours',
      'provider': 'Multiple',
    },
    {
      'name': 'Data Science Professional',
      'duration': '180 hours',
      'provider': 'IBM/Coursera',
    },
    {
      'name': 'AI & Machine Learning',
      'duration': '160 hours',
      'provider': 'Stanford/DeepLearning.ai',
    },
    {
      'name': 'Digital Marketing Certification',
      'duration': '80 hours',
      'provider': 'Google',
    },
    {
      'name': 'Project Management Professional (PMP)',
      'duration': '120 hours',
      'provider': 'PMI',
    },
    {'name': 'Six Sigma Green Belt', 'duration': '40 hours', 'provider': 'ASQ'},
    {
      'name': 'SAP FICO Certification',
      'duration': '150 hours',
      'provider': 'SAP',
    },
    {
      'name': 'Tally ERP 9 Certification',
      'duration': '60 hours',
      'provider': 'Tally',
    },
    {
      'name': 'Blockchain Certification',
      'duration': '50 hours',
      'provider': 'Blockchain Council',
    },
    {
      'name': 'DevOps Certification',
      'duration': '80 hours',
      'provider': 'Various',
    },
    {
      'name': 'Cloud Computing Certification',
      'duration': '60 hours',
      'provider': 'Various',
    },
    {
      'name': 'Cybersecurity Certification',
      'duration': '70 hours',
      'provider': 'ISC2',
    },
  ];

  // ==================== GETTER METHODS ====================
  static List<String> getTwelfthStreams() =>
      twelfthStreamsWithSubjects.keys.toList();
  static List<String> getSubjectsForStream(String stream) =>
      twelfthStreamsWithSubjects[stream] ?? [];
  static List<String> getDegreeNames() =>
      allDegrees.map((d) => d['name'] as String).toList();
  static List<String> getDegreeFullNames() =>
      allDegrees.map((d) => d['fullName'] as String).toList();
  static List<String> getDegreeTypes() =>
      allDegrees.map((d) => d['type'] as String).toSet().toList();

  static List<Map<String, dynamic>> getDegreesByType(String type) {
    return allDegrees.where((degree) => degree['type'] == type).toList();
  }

  static List<String> getDegreeNamesByType(String type) {
    return getDegreesByType(type).map((d) => d['name'] as String).toList();
  }

  static List<String> getEngineeringBranches() => engineeringBranches;
  static List<String> getScienceSubjects() => scienceSubjects;
  static List<String> getCommerceSubjects() => commerceSubjects;
  static List<String> getArtsSubjects() => artsSubjects;
  static List<String> getManagementSubjects() => managementSubjects;
  static List<String> getComputerSubjects() => computerSubjects;
  static List<String> getMedicalSubjects() => medicalSubjects;
  static List<String> getLawSubjects() => lawSubjects;
  static List<String> getAgricultureSubjects() => agricultureSubjects;
  static List<String> getItiTradeNames() =>
      itiTrades.map((t) => t['name']!).toList();
  static List<String> getDiplomaCourseNames() =>
      diplomaCourses.map((d) => d['name']!).toList();
  static List<String> getCertificationNames() =>
      certifications.map((c) => c['name']!).toList();

  static List<String> getAllSubjectsByDegreeType(String degreeType) {
    switch (degreeType) {
      case 'Engineering':
        return engineeringBranches;
      case 'Science':
        return scienceSubjects;
      case 'Commerce':
        return commerceSubjects;
      case 'Arts':
        return artsSubjects;
      case 'Management':
        return managementSubjects;
      case 'Computer':
        return computerSubjects;
      case 'Medical':
        return medicalSubjects;
      case 'Law':
        return lawSubjects;
      case 'Agriculture':
        return agricultureSubjects;
      default:
        return [];
    }
  }

  static String getDegreeDuration(String degreeName) {
    final degree = allDegrees.firstWhere(
      (d) => d['name'] == degreeName,
      orElse: () => {'duration': 'N/A'},
    );
    return degree['duration'] as String;
  }

  static String getDegreeFullName(String degreeName) {
    final degree = allDegrees.firstWhere(
      (d) => d['name'] == degreeName,
      orElse: () => {'fullName': degreeName},
    );
    return degree['fullName'] as String;
  }
}
