analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - lib/features/payment/razorpay_web_service.dart
    - lib/core/widgets/web_pdf_viewer_web.dart

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: true
    prefer_final_fields: true
    unnecessary_this: true
    use_key_in_widget_constructors: true